### PR TITLE
Added Cake build script

### PR DESCRIPTION
**Pull request by jchannon**

### CODE REVIEW

**Comment by khellang** [comment]
Do we really want to maintain these in all the repos? Isn't this what Nancy.Build is for? :confused:

**Comment by grumpydev** [comment]
There's rakefiles in each project currently so you can build them in isolation.. the build script of doom is just for releases.

**Comment by jchannon** [comment]
I assume I can remove the need for a MonoRelease being passed to `dotnet build`, previously Albacore had separate `xbuild` properties etc

**Comment by khellang** [comment]
We use that on Mono for some ifdefs etc.. I still think those should be used.

**Comment by jchannon** [comment]
This can be merged, might want to use Github squash and merge feature. Thanks!!

**Pull request merged**
